FROM python:3.9-alpine

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt || true
RUN python3 -m unittest discover -s . -p "Test*.py"

COPY . .

CMD ["uvicorn", "calculator:app", "--host", "0.0.0.0", "--port", "8000"]